name = "cool"

colors = [
    "#2166ac",
    "#4393c3",
    "#66bd63",
    "#1a9850",
    "#762a83",
    "#9970ab",
    "#35978f",
    "#80cdc1",
    "#d6604d",
    "#f4a582",
]

[dark]
colors = [
    "#5a9ad5",
    "#7ab8e0",
    "#8ed88a",
    "#4fc07a",
    "#a060b0",
    "#c0a0d0",
    "#60c0b5",
    "#a0e0d8",
    "#e58370",
    "#f7c2a3",
]
