name = "vivid"

colors = [
    "#e6194b",
    "#3cb44b",
    "#ffe119",
    "#4363d8",
    "#f58231",
    "#911eb4",
    "#42d4f4",
    "#f032e6",
]

[dark]
colors = [
    "#ff4070",
    "#60d870",
    "#fff050",
    "#6080f0",
    "#ffa060",
    "#c050e0",
    "#60e8ff",
    "#ff60f0",
]
