import html
import re
from pathlib import Path

from ._compat import tomllib

import markdown
import bleach
from bleach.css_sanitizer import CSSSanitizer
from jinja2 import Environment, FileSystemLoader

# Bundled templates directory (inside the package)
BUNDLED_TEMPLATES_DIR = Path(__file__).parent / "templates" / "default"

# --- CONFIGURATION: Security & Sanitization ---
ALLOWED_TAGS = list(bleach.sanitizer.ALLOWED_TAGS) + [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'div', 'span', 'br', 'hr',
    'ul', 'ol', 'li', 'blockquote', 'pre', 'code',
    'table', 'thead', 'tbody', 'tr', 'th', 'td', 'caption',
    'img', 'iframe'
]

ALLOWED_ATTRIBUTES = {
    '*': ['class', 'id', 'style', 'title'],
    'a': ['href', 'target', 'rel'],
    'img': ['src', 'alt', 'width', 'height'],
    'iframe': ['src', 'width', 'height', 'allowfullscreen', 'frameborder', 'allow'],
    'div': ['class', 'id', 'style', 'data-chart-type', 'data-chart-options', 'data-chart-title'],
    'th': ['class', 'scope'],
}

MD_EXTENSIONS = ['tables', 'sane_lists', 'nl2br', 'fenced_code', 'footnotes']

_SLIDE_SPLIT_RE = re.compile(r'\n+[ \t]*---[ \t]*\n+')
_AUTOLINK_RE = re.compile(r'(?<!["\x27=])(https?://[^\s<>\x27"]+)')
_FRONTMATTER_RE = re.compile(r'\A\s*\+\+\+\n(.*?)\n\+\+\+\n?', re.DOTALL)
_CHART_DIRECTIVE_RE = re.compile(
    r'^:::chart\s+(\S+)(.*?)\n(.*?)\n:::',
    re.MULTILINE | re.DOTALL
)
_VALID_CHART_TYPES = {'bar', 'column', 'line', 'area', 'pie'}
_CHART_DIV_RE = re.compile(
    r'<div class="md2-chart" data-chart-type="(\w+)" '
    r'data-chart-options="([^"]*)"'
    r'(?:\s+data-chart-title="([^"]*)")?'
    r'>(.*?)</div>',
    re.DOTALL
)

DEFAULT_THEME = {
    "bg_color": "#f9f9f9",
    "text_color": "#333",
    "sidebar_bg": "#ffffff",
    "h2_color": "#333",
    "font_family": '"Ubuntu", sans-serif'
}


def parse_frontmatter(markdown_text):
    """Extract TOML frontmatter delimited by +++ and return (metadata, body).

    If no frontmatter is found, returns ({}, original_text).
    Raises ValueError on malformed TOML.
    """
    match = _FRONTMATTER_RE.match(markdown_text)
    if not match:
        return {}, markdown_text

    toml_str = match.group(1)
    body = markdown_text[match.end():]

    if not toml_str.strip():
        return {}, body

    try:
        metadata = tomllib.loads(toml_str)
    except Exception as e:
        raise ValueError(f"Invalid TOML in frontmatter: {e}") from e

    return metadata, body


def _parse_chart_options(options_str):
    """Parse chart option flags and title from the directive line."""
    options = []
    title = ""
    parts = options_str.split()
    i = 0
    while i < len(parts):
        part = parts[i]
        if part == '--title' and i + 1 < len(parts):
            # Collect title: may be quoted ("multi word") or a single token
            i += 1
            if parts[i].startswith('"'):
                title_tokens = [parts[i]]
                while i < len(parts) and not parts[i].endswith('"'):
                    i += 1
                    if i < len(parts):
                        title_tokens.append(parts[i])
                title = " ".join(title_tokens).strip('"')
            else:
                title = parts[i]
        elif part.startswith('--'):
            options.append(part[2:])
        i += 1
    return options, title


def preprocess_chart_directives(markdown_text):
    """Find :::chart ... ::: blocks, parse tables, and produce chart HTML.

    Returns (modified_markdown, has_charts).
    Each chart block is replaced with fully-formed chart HTML (using
    markdown to parse the table independently).
    """
    has_charts = False

    def _replace_chart(match):
        nonlocal has_charts
        chart_type = match.group(1).strip().lower()
        options_str = match.group(2).strip()
        table_md = match.group(3)

        if chart_type not in _VALID_CHART_TYPES:
            return table_md

        has_charts = True

        options, title = _parse_chart_options(options_str)
        opts_attr = ",".join(options)
        title_attr = f' data-chart-title="{html.escape(title)}"' if title else ""

        # Parse table markdown independently
        table_html = markdown.markdown(table_md.strip(), extensions=['tables'])

        return (
            f'<div class="md2-chart" data-chart-type="{chart_type}" '
            f'data-chart-options="{opts_attr}"{title_attr}>'
            f'{table_html}'
            f'</div>'
        )

    result = _CHART_DIRECTIVE_RE.sub(_replace_chart, markdown_text)
    return result, has_charts


def transform_charts(html_content):
    """Post-process HTML to convert marked chart divs into Charts.css structure.

    Finds <div class="md2-chart"> wrappers and transforms the <table> inside
    into the structure Charts.css expects.

    Note: the table HTML inside chart divs is generated by markdown.markdown()
    in preprocess_chart_directives, then passes through sanitize_html(). The
    regex extraction here assumes clean markdown-generated table tags without
    extra attributes. This is safe because the input is controlled.
    """
    def _transform_chart(match):
        chart_type = match.group(1)
        options_str = match.group(2)
        chart_title = match.group(3) or ""
        inner_html = match.group(4)

        options = set(options_str.split(",")) if options_str else set()

        # Parse the HTML table
        headers = re.findall(r'<th>(.*?)</th>', inner_html)
        rows = re.findall(r'<tr>(.*?)</tr>', inner_html, re.DOTALL)

        # Skip header row(s) — find data rows (those with <td>)
        data_rows = []
        for row_html in rows:
            cells = re.findall(r'<td>(.*?)</td>', row_html)
            if cells:
                # First cell is label, rest are data
                row_th = re.findall(r'<th>(.*?)</th>', row_html)
                label = row_th[0] if row_th else cells[0]
                values = cells if not row_th else cells
                if row_th:
                    data_rows.append((label, values))
                else:
                    data_rows.append((cells[0], cells[1:]))

        if not data_rows:
            return match.group(0)  # No data, return unchanged

        # Determine if multi-dataset
        num_datasets = len(data_rows[0][1]) if data_rows else 0
        is_multiple = num_datasets > 1

        # Collect all numeric values for normalization
        all_values = []
        for _, values in data_rows:
            for v in values:
                try:
                    all_values.append(float(v.strip()))
                except (ValueError, TypeError):
                    all_values.append(0)

        max_val = max(all_values) if all_values and max(all_values) > 0 else 1

        # Dataset headers (for legend)
        dataset_headers = headers[1:] if len(headers) > 1 else []

        # Build CSS classes
        classes = ["charts-css", chart_type]
        if is_multiple:
            classes.append("multiple")
        if "labels" in options:
            classes.append("show-labels")
        if "stacked" in options:
            classes.append("stacked")
        if "show-data" in options:
            classes.append("show-data-on-hover")

        class_str = " ".join(classes)

        # Build new table HTML
        parts = [f'<table class="{class_str}">']

        if chart_title:
            parts.append(f'<caption>{chart_title}</caption>')

        # Thead
        parts.append('<thead><tr>')
        parts.append(f'<th scope="col">{headers[0] if headers else "Label"}</th>')
        for h in dataset_headers:
            parts.append(f'<th scope="col">{h}</th>')
        parts.append('</tr></thead>')

        # Tbody
        parts.append('<tbody>')
        val_idx = 0
        for label, values in data_rows:
            parts.append('<tr>')
            parts.append(f'<th scope="row">{label}</th>')
            for v in values:
                norm = all_values[val_idx] / max_val
                # Format: avoid trailing zeros, but keep precision
                size_str = f"{norm:g}" if norm != int(norm) else str(int(norm))
                data_span = f'<span class="data">{v.strip()}</span>'
                parts.append(f'<td style="--size: {size_str}">{data_span}</td>')
                val_idx += 1
            parts.append('</tr>')
        parts.append('</tbody>')
        parts.append('</table>')

        result = "\n".join(parts)

        # Add legend if requested
        if "legend" in options and dataset_headers:
            legend_items = "".join(f'<li>{h}</li>' for h in dataset_headers)
            result += f'\n<ul class="charts-css legend legend-inline">{legend_items}</ul>'

        return f'<div class="md2-chart">{result}</div>'

    return _CHART_DIV_RE.sub(_transform_chart, html_content)


def sanitize_html(html_content):
    """Cleans HTML to prevent XSS while allowing safe tags."""
    return bleach.clean(
        html_content,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        css_sanitizer=CSSSanitizer(),
        strip=True
    )


def autolink(html_content):
    """Converts bare URLs in HTML text into clickable <a> links."""
    return _AUTOLINK_RE.sub(
        r'<a href="\1" target="_blank" rel="noopener">\1</a>',
        html_content
    )


def process_markdown(text):
    """Converts markdown text to sanitized, autolinked HTML.

    Returns (html_string, has_charts) tuple.
    """
    text, has_charts = preprocess_chart_directives(text)
    raw_html = markdown.markdown(text, extensions=MD_EXTENSIONS)
    sanitized = sanitize_html(raw_html)
    result = autolink(sanitized)
    if has_charts:
        result = transform_charts(result)
    return result, has_charts


def prepare_context(markdown_text, metadata=None):
    """
    Parses markdown into a context dict for template rendering.
    Returns a dict with 'title', 'cover', 'slides', and frontmatter fields.
    """
    if metadata is None:
        metadata = {}

    raw_slides = _SLIDE_SPLIT_RE.split(markdown_text)

    cover_title = "Presentation"
    cover_content = ""

    if raw_slides:
        first_slide_text = raw_slides[0].strip()
        lines = first_slide_text.split('\n')
        if lines and lines[0].startswith('# '):
            cover_title = lines[0][2:].strip()
            cover_content = '\n'.join(lines[1:])
        else:
            cover_content = first_slide_text

    # Frontmatter title overrides H1 for the presentation title
    if "title" in metadata:
        cover_title = metadata["title"]

    has_charts = False
    slides_data = []
    for i, slide_text in enumerate(raw_slides[1:]):
        slide_text = slide_text.strip()
        lines = slide_text.split('\n')
        slide_title = f"Slide {i + 1}"
        slide_body = slide_text

        if lines and lines[0].startswith('## '):
            slide_title = lines[0][3:].strip()
            slide_body = '\n'.join(lines[1:])

        content, slide_has_charts = process_markdown(slide_body)
        if slide_has_charts:
            has_charts = True
        slides_data.append({
            "id": f"slide-{i}",
            "title": slide_title,
            "content": content
        })

    cover_clean, cover_has_charts = process_markdown(cover_content)
    if cover_has_charts:
        has_charts = True

    return {
        "title": cover_title,
        "cover": {
            "title": cover_title,
            "content": cover_clean
        },
        "slides": slides_data,
        "palette": metadata.get("palette", "default"),
        "colors": metadata.get("colors"),
        "has_charts": has_charts,
    }


def extract_og_description(markdown_text, fallback_title):
    """Extract OG description from cover section of markdown."""
    og_desc_lines = []
    for line in markdown_text.split('\n'):
        line = line.strip()
        if line.startswith('#') or line == '---':
            if line == '---':
                break
            continue
        if line:
            og_desc_lines.append(line)
        if len(og_desc_lines) >= 2:
            break
    return html.escape(' '.join(og_desc_lines)[:200] if og_desc_lines else fallback_title)


def get_jinja_env(template_dir=None):
    """Create a Jinja2 Environment for the given template directory (or bundled default)."""
    if template_dir is None:
        template_dir = BUNDLED_TEMPLATES_DIR
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=False,
    )
